apiVersion: v1
kind: Service
metadata:
  name: blue-coding-app-service
spec:
  selector:
    app: blue-coding-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
